/**
 * lib/experience-context/fan-slides.ts
 * 
 * ファン視点の追体験スライドデータ
 */
import type { ExperienceSlide } from "./types";

export const FAN_EXPERIENCE_SLIDES: ExperienceSlide[] = [
  // --- イントロ ---
  {
    id: "fan-intro",
    character: "rinku",
    message: "ファンの追体験へようこそ！",
    subMessage: "推しのチャレンジに参加して、ファン同士で繋がる流れを体験しよう",
    thought: "これからファンとしての使い方を説明するね！",
    previewType: "none",
    backgroundColor: "#1a1a2e",
    stepNumber: 0,
    stepTitle: "はじめに",
  },

  // --- STEP 1: チャレンジを発見する ---
  {
    id: "fan-1",
    character: "konta",
    message: "推しのチャレンジを発見！",
    subMessage: "ホーム画面で注目のチャレンジや、カテゴリ別のチャレンジを探せる",
    thought: "お、推しの新しいチャレンジがある！\nさっそくチェックしよう",
    previewType: "challenge-card",
    backgroundColor: "#16213e",
    stepNumber: 1,
    stepTitle: "チャレンジ発見",
  },
  {
    id: "fan-2",
    character: "tanune",
    message: "通知で見逃さない！",
    subMessage: "お気に入りアーティストを登録しておくと、新しいチャレンジが通知される",
    thought: "通知が来た！\n推しの新しいチャレンジだ！",
    previewType: "notification",
    backgroundColor: "#1a1a2e",
    stepNumber: 1,
    stepTitle: "チャレンジ発見",
  },
  {
    id: "fan-3",
    character: "rinku",
    message: "チャレンジの詳細をチェック",
    subMessage: "目標人数、開催日、チケット情報などを確認しよう",
    thought: "100人動員チャレンジか！\n今30人だから、私も参加しよう！",
    previewType: "progress-bar",
    backgroundColor: "#16213e",
    stepNumber: 1,
    stepTitle: "チャレンジ発見",
  },

  // --- STEP 2: 参加表明する ---
  {
    id: "fan-4",
    character: "konta",
    message: "参加表明ボタンをタップ！",
    subMessage: "「参加する」ボタンを押して、参加表明フォームを開こう",
    thought: "よし、参加表明しよう！\n推しに気持ちを伝えたい！",
    previewType: "form",
    backgroundColor: "#1a1a2e",
    stepNumber: 2,
    stepTitle: "参加表明",
  },
  {
    id: "fan-5",
    character: "tanune",
    message: "応援メッセージを書こう",
    subMessage: "推しへの気持ちを込めたメッセージを送れる",
    thought: "「いつも応援してます！」\n「今回のライブ、絶対行きます！」",
    previewType: "comment",
    backgroundColor: "#16213e",
    stepNumber: 2,
    stepTitle: "参加表明",
  },
  {
    id: "fan-6",
    character: "rinku",
    message: "参加する都道府県を選択",
    subMessage: "どこから参加するか伝えて、遠方参加をアピール！",
    thought: "福岡から東京のライブに参加するんだ！\n遠方から来てること、知ってほしいな",
    previewType: "prefecture",
    backgroundColor: "#1a1a2e",
    stepNumber: 2,
    stepTitle: "参加表明",
  },
  {
    id: "fan-7",
    character: "konta",
    message: "友達も一緒に誘える！",
    subMessage: "「+○人連れて行く」で、友達の分も参加表明できる",
    thought: "友達も誘ったから、\n+2人で参加表明しよう！",
    previewType: "invite",
    backgroundColor: "#16213e",
    stepNumber: 2,
    stepTitle: "参加表明",
  },

  // --- STEP 3: 参加完了！ ---
  {
    id: "fan-8",
    character: "tanune",
    message: "参加表明完了！🎉",
    subMessage: "参加表明が完了すると、進捗バーに反映される",
    thought: "やった！参加表明できた！\n進捗バーが少し伸びた！",
    previewType: "progress-bar",
    backgroundColor: "#1a1a2e",
    stepNumber: 3,
    stepTitle: "参加完了",
  },
  {
    id: "fan-9",
    character: "rinku",
    message: "SNSでシェアして盛り上げよう",
    subMessage: "参加表明をTwitterでシェアして、他のファンにも広めよう",
    thought: "参加表明したこと、シェアしよう！\n他のファンも誘いたい！",
    previewType: "share",
    backgroundColor: "#16213e",
    stepNumber: 3,
    stepTitle: "参加完了",
  },

  // --- STEP 4: 他のファンを発見 ---
  {
    id: "fan-10",
    character: "konta",
    message: "参加者一覧をチェック！",
    subMessage: "同じチャレンジに参加している他のファンを発見できる",
    thought: "他にどんなファンがいるんだろう？\n参加者一覧を見てみよう",
    previewType: "participants",
    backgroundColor: "#1a1a2e",
    stepNumber: 4,
    stepTitle: "ファン発見",
  },
  {
    id: "fan-11",
    character: "tanune",
    message: "同じ県のファンを発見！",
    subMessage: "地域別で絞り込むと、近くのファンが見つかる",
    thought: "あ、同じ福岡県のファンがいる！\n一緒に遠征できるかも！",
    previewType: "participants",
    backgroundColor: "#16213e",
    stepNumber: 4,
    stepTitle: "ファン発見",
  },
  {
    id: "fan-12",
    character: "rinku",
    message: "気になるファンのプロフィール",
    subMessage: "Twitterアカウントやプロフィールを見て、共通点を探そう",
    thought: "この人、他のアーティストも好きなんだ！\n趣味が合いそう！",
    previewType: "profile",
    backgroundColor: "#1a1a2e",
    stepNumber: 4,
    stepTitle: "ファン発見",
  },

  // --- STEP 5: ファンと繋がる ---
  {
    id: "fan-13",
    character: "konta",
    message: "フォローして繋がろう！",
    subMessage: "気になるファンをフォローして、ファンコミュニティを広げよう",
    thought: "この人、フォローしよう！\nライブの話とかしたいな",
    previewType: "profile",
    backgroundColor: "#16213e",
    stepNumber: 5,
    stepTitle: "ファン交流",
  },
  {
    id: "fan-14",
    character: "tanune",
    message: "影響力のあるファンと繋がる",
    subMessage: "フォロワー数の多いファンをフォローすると、情報が入りやすい",
    thought: "この人、フォロワー1万人もいる！\n有名なファンの人だ！",
    previewType: "influencer",
    backgroundColor: "#1a1a2e",
    stepNumber: 5,
    stepTitle: "ファン交流",
  },
  {
    id: "fan-15",
    character: "rinku",
    message: "DMで直接やり取り",
    subMessage: "気になるファンにDMを送って、仲良くなろう",
    thought: "同じ県だし、一緒に遠征しませんか？\nってDM送ってみよう！",
    previewType: "dm",
    backgroundColor: "#16213e",
    stepNumber: 5,
    stepTitle: "ファン交流",
  },

  // --- STEP 6: イベント当日に向けて ---
  {
    id: "fan-16",
    character: "konta",
    message: "カウントダウンでワクワク！",
    subMessage: "イベント当日までの残り日数がカウントダウンされる",
    thought: "あと7日！\n楽しみすぎる〜！",
    previewType: "countdown",
    backgroundColor: "#1a1a2e",
    stepNumber: 6,
    stepTitle: "当日に向けて",
  },
  {
    id: "fan-17",
    character: "tanune",
    message: "リマインダーを設定",
    subMessage: "イベント前日や当日に通知が届くように設定できる",
    thought: "前日にリマインダー設定しておこう\n準備を忘れないように！",
    previewType: "reminder",
    backgroundColor: "#16213e",
    stepNumber: 6,
    stepTitle: "当日に向けて",
  },
  {
    id: "fan-18",
    character: "rinku",
    message: "チケット情報を確認",
    subMessage: "チケットの購入リンクや価格を再確認しよう",
    thought: "チケット、ちゃんと買ったかな？\n確認しておこう",
    previewType: "ticket",
    backgroundColor: "#1a1a2e",
    stepNumber: 6,
    stepTitle: "当日に向けて",
  },

  // --- STEP 7: 目標達成を見届ける ---
  {
    id: "fan-19",
    character: "konta",
    message: "目標達成！みんなで喜ぼう！",
    subMessage: "100人の参加表明が集まった！達成通知が届く",
    thought: "やった！100人達成！\n私も貢献できた！",
    previewType: "celebration",
    backgroundColor: "#16213e",
    stepNumber: 7,
    stepTitle: "目標達成",
  },
  {
    id: "fan-20",
    character: "tanune",
    message: "達成記念ページに名前が載る！",
    subMessage: "参加者全員の名前が記念ページに掲載される",
    thought: "私の名前も載ってる！\n記念に残るな〜",
    previewType: "achievement",
    backgroundColor: "#1a1a2e",
    stepNumber: 7,
    stepTitle: "目標達成",
  },
  {
    id: "fan-21",
    character: "rinku",
    message: "バッジをゲット！",
    subMessage: "参加するとバッジがもらえる。たくさん集めよう！",
    thought: "参加バッジゲット！\nマイページに飾られるんだ！",
    previewType: "badge",
    backgroundColor: "#16213e",
    stepNumber: 7,
    stepTitle: "目標達成",
  },

  // --- STEP 8: 貢献度ランキング ---
  {
    id: "fan-22",
    character: "konta",
    message: "貢献度ランキングをチェック",
    subMessage: "友達を誘った数や参加回数でランキングが決まる",
    thought: "私、貢献度ランキング5位だ！\nもっと上を目指したい！",
    previewType: "ranking",
    backgroundColor: "#1a1a2e",
    stepNumber: 8,
    stepTitle: "ランキング",
  },
  {
    id: "fan-23",
    character: "tanune",
    message: "常連ファンバッジをゲット！",
    subMessage: "何度も参加すると、常連ファンバッジがもらえる",
    thought: "常連ファンバッジ、嬉しい！\n推しに認知されてる気分！",
    previewType: "crown",
    backgroundColor: "#16213e",
    stepNumber: 8,
    stepTitle: "ランキング",
  },

  // --- エンディング ---
  {
    id: "fan-end",
    character: "kimitolink",
    message: "ファンの追体験は以上です！",
    subMessage: "さあ、推しのチャレンジに参加して、ファン同士で繋がろう！",
    thought: "動員ちゃれんじで、\n推し活をもっと楽しもう！",
    previewType: "none",
    backgroundColor: "#1a1a2e",
    stepNumber: 9,
    stepTitle: "おわりに",
  },
];
