/**
 * lib/experience-context/organizer-slides.ts
 * 
 * 主催者視点の追体験スライドデータ
 */
import type { ExperienceSlide } from "./types";

export const ORGANIZER_EXPERIENCE_SLIDES: ExperienceSlide[] = [
  // --- STEP 1: チャレンジを作成する ---
  {
    id: "org-intro",
    character: "kimitolink",
    message: "主催者の追体験へようこそ！",
    subMessage: "チャレンジを作成して、ファンと一緒に目標を達成する流れを体験しよう",
    thought: "これから君斗りんくのすれ違ひ通信の使い方を説明するね！",
    previewType: "none",
    backgroundColor: "#1a1a2e",
    stepNumber: 0,
    stepTitle: "はじめに",
  },
  {
    id: "org-1",
    character: "rinku",
    message: "まずはチャレンジを作成！",
    subMessage: "ライブやイベントの目標人数を設定して、ファンに参加を呼びかけよう",
    thought: "来月のライブ、100人集めたいな...\nチャレンジを作って告知しよう！",
    previewType: "form",
    backgroundColor: "#16213e",
    stepNumber: 1,
    stepTitle: "チャレンジ作成",
  },
  {
    id: "org-2",
    character: "konta",
    message: "チケット情報も設定できる",
    subMessage: "前売り・当日券の価格や購入リンクを設定して、ファンが迷わないように",
    thought: "チケット情報も入れておけば\nファンが購入しやすいね",
    previewType: "ticket",
    backgroundColor: "#1a1a2e",
    stepNumber: 1,
    stepTitle: "チャレンジ作成",
  },
  {
    id: "org-3",
    character: "tanune",
    message: "カテゴリを選んで見つけやすく",
    subMessage: "アイドル、バンド、VTuberなど、カテゴリを設定すると検索されやすい",
    thought: "カテゴリを設定しておけば\n新しいファンにも見つけてもらえるかも！",
    previewType: "chart",
    backgroundColor: "#16213e",
    stepNumber: 1,
    stepTitle: "チャレンジ作成",
  },

  // --- STEP 2: 告知・拡散する ---
  {
    id: "org-4",
    character: "rinku",
    message: "SNSでシェアして告知！",
    subMessage: "作成したチャレンジをTwitterでシェアして、ファンに知らせよう",
    thought: "チャレンジ作成完了！\nさっそくTwitterで告知しよう",
    previewType: "share",
    backgroundColor: "#1a1a2e",
    stepNumber: 2,
    stepTitle: "告知・拡散",
  },
  {
    id: "org-5",
    character: "konta",
    message: "OGP画像が自動生成される",
    subMessage: "シェアすると、進捗状況が見えるカードが自動で作られる",
    thought: "シェアしたら自動でカード画像が\n作られるから便利だね",
    previewType: "challenge-card",
    backgroundColor: "#16213e",
    stepNumber: 2,
    stepTitle: "告知・拡散",
  },

  // --- STEP 3: 参加者が増えていく ---
  {
    id: "org-6",
    character: "tanune",
    message: "参加表明が届き始める！",
    subMessage: "ファンからの参加表明と応援メッセージが届く",
    thought: "わ！さっそく参加表明が来た！\n嬉しいな〜",
    previewType: "notification",
    backgroundColor: "#1a1a2e",
    stepNumber: 3,
    stepTitle: "参加者増加",
  },
  {
    id: "org-7",
    character: "rinku",
    message: "進捗バーがどんどん伸びる！",
    subMessage: "目標に向かって進捗バーが伸びていく様子が見える",
    thought: "もう30%達成！\nこのペースなら100人いけそう！",
    previewType: "progress-bar",
    backgroundColor: "#16213e",
    stepNumber: 3,
    stepTitle: "参加者増加",
  },
  {
    id: "org-8",
    character: "konta",
    message: "全国から参加者が！",
    subMessage: "地図で参加者の分布が見える。遠方からの参加者も！",
    thought: "北海道からも参加表明が！\n全国から来てくれるんだ！",
    previewType: "map",
    backgroundColor: "#1a1a2e",
    stepNumber: 3,
    stepTitle: "参加者増加",
  },
  {
    id: "org-9",
    character: "tanune",
    message: "応援メッセージが届く",
    subMessage: "ファンからの熱いメッセージが届いて、モチベーションアップ！",
    thought: "「絶対行きます！」「楽しみにしてます！」\n嬉しいメッセージがたくさん！",
    previewType: "comment",
    backgroundColor: "#16213e",
    stepNumber: 3,
    stepTitle: "参加者増加",
  },

  // --- STEP 4: ファンとコミュニケーション ---
  {
    id: "org-10",
    character: "rinku",
    message: "ランキングで盛り上げる",
    subMessage: "貢献度ランキングで、熱心なファンが見える",
    thought: "この人、いつも応援してくれてる！\n感謝を伝えたいな",
    previewType: "ranking",
    backgroundColor: "#1a1a2e",
    stepNumber: 4,
    stepTitle: "コミュニケーション",
  },
  {
    id: "org-11",
    character: "konta",
    message: "DMで直接お礼を伝える",
    subMessage: "特に貢献してくれたファンにDMでお礼を伝えられる",
    thought: "いつも応援ありがとう！\nDMでお礼を伝えよう",
    previewType: "dm",
    backgroundColor: "#16213e",
    stepNumber: 4,
    stepTitle: "コミュニケーション",
  },
  {
    id: "org-12",
    character: "tanune",
    message: "リマインダーで呼びかけ",
    subMessage: "イベント直前にリマインダーを送って、参加を促せる",
    thought: "明日がライブ！\nリマインダーを送っておこう",
    previewType: "reminder",
    backgroundColor: "#1a1a2e",
    stepNumber: 4,
    stepTitle: "コミュニケーション",
  },

  // --- STEP 5: 目標達成！ ---
  {
    id: "org-13",
    character: "rinku",
    message: "目標達成！🎉",
    subMessage: "100人達成！ファンと一緒に喜びを分かち合おう",
    thought: "やった！100人達成！\nみんなのおかげだ！",
    previewType: "celebration",
    backgroundColor: "#1a1a2e",
    stepNumber: 5,
    stepTitle: "目標達成",
  },
  {
    id: "org-14",
    character: "konta",
    message: "達成バッジを獲得！",
    subMessage: "目標達成でバッジがもらえる。次の目標に向けて頑張ろう！",
    thought: "達成バッジゲット！\n次は200人を目指そう！",
    previewType: "badge",
    backgroundColor: "#16213e",
    stepNumber: 5,
    stepTitle: "目標達成",
  },
  {
    id: "org-15",
    character: "tanune",
    message: "統計で振り返り",
    subMessage: "参加者の傾向や、盛り上がりの推移を確認できる",
    thought: "今回は関東からの参加が多かったな\n次は関西でもやってみよう",
    previewType: "stats",
    backgroundColor: "#1a1a2e",
    stepNumber: 5,
    stepTitle: "目標達成",
  },

  // --- 終了 ---
  {
    id: "org-end",
    character: "kimitolink",
    message: "主催者の追体験、完了！",
    subMessage: "さっそくチャレンジを作成して、ファンと一緒に目標を達成しよう！",
    thought: "これで主催者の流れはバッチリ！\nさっそくチャレンジを作ってみよう！",
    previewType: "none",
    backgroundColor: "#1a1a2e",
    stepNumber: 6,
    stepTitle: "完了",
  },
];
