/**
 * app/visit.tsx から切り出したスタイル定義。
 * visit-screen-view.tsx から参照される。
 */
import { StyleSheet } from "react-native";
import { color, palette } from "@/theme/tokens";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#07111F",
  },
  content: {
    width: "100%",
    maxWidth: 980,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 44,
    gap: 14,
  },
  heroBand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(20,184,166,0.38)",
    backgroundColor: "rgba(10,22,38,0.92)",
    padding: 16,
  },
  heroIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: color.accentPrimary,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  heroTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  eyebrow: {
    color: color.teal500,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0,
    marginBottom: 3,
  },
  heroTitle: {
    color: color.textWhite,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0,
  },
  heroCopy: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  formPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.96)",
    padding: 16,
    gap: 12,
  },
  sectionLabel: {
    color: color.textPrimary,
    fontSize: 14,
    fontWeight: "900",
  },
  inputGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  inputBlock: {
    flex: 1,
    minWidth: 220,
    gap: 6,
  },
  inputLabel: {
    color: color.textSecondary,
    fontSize: 12,
    fontWeight: "800",
  },
  input: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.border,
    backgroundColor: palette.white,
    color: color.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  noteInput: {
    minHeight: 76,
    textAlignVertical: "top",
  },
  pinPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.border,
    backgroundColor: "rgba(10,22,38,0.04)",
    padding: 12,
    gap: 10,
  },
  pinHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pinIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: color.accentIndigo,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pinHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  pinTitle: {
    color: color.textPrimary,
    fontSize: 14,
    fontWeight: "900",
  },
  pinSub: {
    color: color.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  pinActions: {
    gap: 10,
  },
  primaryPinButton: {
    minHeight: 52,
    borderRadius: 10,
    backgroundColor: color.accentPrimary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  primaryPinButtonText: {
    color: color.textWhite,
    fontSize: 15,
    fontWeight: "900",
  },
  coordToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 4,
  },
  coordToggleText: {
    color: color.textMuted,
    fontSize: 13,
    fontWeight: "700",
  },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: color.accentIndigo,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 14,
    flexShrink: 0,
  },
  secondaryButtonDisabled: {
    backgroundColor: color.borderAlt,
  },
  secondaryButtonText: {
    color: color.textWhite,
    fontSize: 13,
    fontWeight: "900",
  },
  coordinateGroup: {
    flex: 1,
    minWidth: 260,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  coordinateInput: {
    flex: 1,
    minWidth: 210,
  },
  coordinateButton: {
    minHeight: 46,
    minWidth: 132,
    borderRadius: 8,
    backgroundColor: color.accentPrimary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    flexShrink: 0,
  },
  coordinateButtonText: {
    color: color.textWhite,
    fontSize: 13,
    fontWeight: "900",
  },
  pinMetaRow: {
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.success + "44",
    backgroundColor: color.success + "10",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 10,
  },
  pinMetaText: {
    color: color.textPrimary,
    fontSize: 12,
    fontWeight: "800",
    flex: 1,
  },
  pinPreviewMap: {
    width: "100%",
  },
  pinEmptyLine: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.border,
    backgroundColor: palette.white,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
  },
  pinEmptyText: {
    color: color.textMuted,
    fontSize: 12,
    lineHeight: 17,
    flex: 1,
  },
  reportButton: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: color.accentPrimary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  reportButtonDisabled: {
    backgroundColor: color.borderAlt,
  },
  reportButtonText: {
    color: color.textWhite,
    fontSize: 15,
    fontWeight: "900",
  },
  statusBar: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: color.success + "55",
    backgroundColor: color.success + "12",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
  },
  errorBar: {
    borderColor: color.danger + "55",
    backgroundColor: color.danger + "12",
  },
  statusText: {
    color: color.textPrimary,
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  errorText: {
    color: color.danger,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingVertical: 14,
    alignItems: "center",
    gap: 4,
  },
  summaryValue: {
    color: color.accentPrimary,
    fontSize: 25,
    fontWeight: "900",
  },
  summaryLabel: {
    color: color.textMuted,
    fontSize: 11,
    fontWeight: "800",
  },
  mapPanel: {
    alignItems: "center",
  },
  mapFrame: {
    width: "100%",
  },
  emptyMap: {
    minHeight: 260,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    gap: 8,
  },
  emptyTitle: {
    color: color.textPrimary,
    fontSize: 16,
    fontWeight: "900",
  },
  emptyText: {
    color: color.textMuted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  listHeader: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  latestText: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 11,
    fontWeight: "700",
  },
  reportRow: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.96)",
    padding: 12,
    flexDirection: "row",
    gap: 12,
  },
  pinBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: color.accentAlt,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  reportBody: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  reportTopLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  reportName: {
    color: color.textPrimary,
    fontSize: 14,
    fontWeight: "900",
    flex: 1,
  },
  reportTime: {
    color: color.textMuted,
    fontSize: 11,
    fontWeight: "700",
    flexShrink: 0,
  },
  reportPlace: {
    color: color.textSecondary,
    fontSize: 13,
    fontWeight: "800",
  },
  reportNote: {
    color: color.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  reportMeta: {
    color: color.textMuted,
    fontSize: 11,
  },
});
